### ISSUE TITLE
Needs setup-fast?

### ISSUE THREAD

**Issue by cocopon** [googkit/googkit#8]
I think the following way is better:

.googkit:

```
library_path=(absolute path)
compiler_path=(absolute path)
```

googkit.cfg:

```
# Commented out, default values used
# library_path=...
# compiler_path=...
```

**Comment by Kuniwak** [comment]
Hi, @cocopon .
I think it is bitty annoying because it needs one step more.
So, I think `setup-fast` is necessary to developers who manage many products, such as me :-)

**Comment by Kuniwak** [comment]
And, `setup-fast` provides clean `googkit.cfg`, it makes easy to develop with other developer.

In the _ancestor directory pattern_ (your solution), other developer have to allocate Closure Library and Closure Compiler as same directory structure.

So, I think the _ancestor directory pattern_ is not good solution.

**Comment by cocopon** [comment]
How about the following solution?
It doesn't require any additional steps.
- Initially all values in googkit.cfg is commented out
- The priority is: default(built-in) < .googkit(global) < googkit.cfg if set(local)

I think keeping simplicity is important for most users, especially newbies.

**Comment by Kuniwak** [comment]
I agree that:

> I think keeping simplicity is important for most users, especially newbies.

But `setup-fast` makes easy to develop with other developer by keeping `googkit.cfg` clean.
For example, `googkit.cfg` is:

```
[library]
root=../closure/library
```

In this case, other developer of the product may get surprise when the other developer execute `googkit setup`, because the Closure Library directory was generated on unexpected location (parent directory of the project root)!
After that, the other developer may wrap the project root and Closure Compiler by a new directory. I think this step is annoying.

**Comment by Kuniwak** [comment]
Thanks @cocopon !
I agree to remove `setup-fast`.
I hope to support a plugin-mechanism!
